'use client';
import { supabase } from '@/lib/supabase/client';
export type Reaction = 'like'|'love'|'laugh'|'idea'|'important'|'celebrate';
export type NoteMedia = { id:string; noteId:string; mediaType:'gif'|'sticker'|'image'; mediaUrl:string; altText:string|null; createdAt:string };
export async function listReactions(noteId:string){const {data,error}=await supabase.from('note_reactions').select('reaction,user_id,created_at').eq('note_id',noteId);if(error)throw error;return data??[];}
export async function toggleReaction(noteId:string,reaction:Reaction){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in first.');const {data:existing}=await supabase.from('note_reactions').select('id').eq('note_id',noteId).eq('user_id',user.id).eq('reaction',reaction).maybeSingle();if(existing){const {error}=await supabase.from('note_reactions').delete().eq('id',existing.id);if(error)throw error;return false;}const {error}=await supabase.from('note_reactions').insert({note_id:noteId,user_id:user.id,reaction});if(error)throw error;return true;}
export async function listNoteMedia(noteId:string){const {data,error}=await supabase.from('note_media').select('id,note_id,media_type,media_url,alt_text,created_at').eq('note_id',noteId).order('created_at',{ascending:false});if(error)throw error;return (data??[]).map((m:any)=>({id:m.id,noteId:m.note_id,mediaType:m.media_type,mediaUrl:m.media_url,altText:m.alt_text,createdAt:m.created_at})) as NoteMedia[];}
export async function addNoteMedia(noteId:string,mediaType:NoteMedia['mediaType'],mediaUrl:string,altText?:string){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in first.');const {data,error}=await supabase.from('note_media').insert({note_id:noteId,user_id:user.id,media_type:mediaType,media_url:mediaUrl.trim(),alt_text:altText?.trim()||null}).select().single();if(error)throw error;return data as NoteMedia;}
export async function removeNoteMedia(id:string){const {error}=await supabase.from('note_media').delete().eq('id',id);if(error)throw error;}
export async function uploadNoteAttachment(noteId:string,file:File){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in first.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${user.id}/${noteId}/${crypto.randomUUID()}-${safe}`;const {data,error}=await supabase.storage.from('note-attachments').upload(path,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw error;const {error:metaError}=await supabase.from('attachments').insert({user_id:user.id,note_id:noteId,file_name:file.name,mime_type:file.type||'application/octet-stream',size_bytes:file.size,storage_path:data.path});if(metaError)throw metaError;return data.path;}
