'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { toast } from 'sonner';
import { loadNotes, saveNotes, loadFolders, saveFolders, hydrateFromCloud, countWords, type Note, type Folder } from '@/lib/notesStorage';
import NotesSidebar from './NotesSidebar';
import NoteEditor from './NoteEditor';
import WebSearchPanel from './WebSearchPanel';
import DashboardHome from './DashboardHome';
import FolderModal from './FolderModal';
import DeleteModal from './DeleteModal';
import AppLogo from '@/components/ui/AppLogo';
import { Menu, X, PanelRight, Search, Moon, Sun, Settings, Command, Plus, LayoutDashboard, FileText, Sparkles, GraduationCap, Briefcase, CalendarDays, BookOpen } from 'lucide-react';
import { useRouter } from 'next/navigation';

export type ActiveView = 'home' | 'editor';
type NoteTemplate = 'blank' | 'daily' | 'study' | 'meeting' | 'project';

const TEMPLATES: Record<NoteTemplate, { label: string; icon: React.ElementType; title: string; content: string }> = {
  blank: { label: 'Blank note', icon: Plus, title: 'Untitled Note', content: '' },
  daily: { label: 'Daily journal', icon: CalendarDays, title: 'Daily Journal', content: '<h2>Today</h2><p><strong>Top priorities</strong></p><ul><li></li><li></li><li></li></ul><p><strong>What I learned</strong></p><p></p><p><strong>Reflection</strong></p><p></p>' },
  study: { label: 'Study notes', icon: GraduationCap, title: 'Study Notes', content: '<h2>Topic</h2><p><strong>Key idea</strong></p><p></p><h3>Important concepts</h3><ul><li></li><li></li><li></li></ul><h3>Questions</h3><ol><li></li><li></li></ol><h3>Summary</h3><p></p>' },
  meeting: { label: 'Meeting notes', icon: Briefcase, title: 'Meeting Notes', content: '<h2>Meeting</h2><p><strong>Date:</strong> </p><p><strong>Attendees:</strong> </p><h3>Agenda</h3><ul><li></li><li></li></ul><h3>Decisions</h3><ul><li></li></ul><h3>Action items</h3><ul><li></li><li></li></ul><h3>Follow-up</h3><p></p>' },
  project: { label: 'Project brief', icon: BookOpen, title: 'Project Brief', content: '<h2>Project goal</h2><p></p><h3>Problem</h3><p></p><h3>Plan</h3><ol><li></li><li></li><li></li></ol><h3>Milestones</h3><ul><li></li><li></li></ul><h3>Next action</h3><p><strong></strong></p>' },
};

export default function DashboardShell() {
  const router = useRouter();
  const [notes, setNotes] = useState<Note[]>([]); const [folders, setFolders] = useState<Folder[]>([]);
  const [activeNoteId, setActiveNoteId] = useState<string | null>(null); const [activeView, setActiveView] = useState<ActiveView>('home');
  const [searchQuery, setSearchQuery] = useState(''); const [sidebarOpen, setSidebarOpen] = useState(true); const [searchPanelOpen, setSearchPanelOpen] = useState(false);
  const [showFolderModal, setShowFolderModal] = useState(false); const [deleteTarget, setDeleteTarget] = useState<string | null>(null); const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false);
  const [insertContent, setInsertContent] = useState<string | null>(null); const [commandOpen, setCommandOpen] = useState(false); const [templateOpen, setTemplateOpen] = useState(false); const [darkMode, setDarkMode] = useState(false);
  const saveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => { let cancelled = false; setNotes(loadNotes()); setFolders(loadFolders()); const stored = localStorage.getItem('smartnotepad_theme'); const dark = stored === 'dark'; setDarkMode(dark); if (dark) document.documentElement.classList.add('dark'); void hydrateFromCloud().then(cloud => { if (!cancelled && cloud) { setNotes(cloud.notes); setFolders(cloud.folders); } }); return () => { cancelled = true; }; }, []);
  const persistNotes = useCallback((updated: Note[]) => saveNotes(updated), []);
  const activeNote = notes.find(n => n.id === activeNoteId) ?? null;

  const createNote = useCallback((template: NoteTemplate = 'blank') => {
    const preset = TEMPLATES[template]; const now = new Date().toISOString(); const newNote: Note = { id: `note-${Date.now()}`, title: preset.title, content: preset.content, folderId: null, isPinned: false, isFavorite: false, createdAt: now, updatedAt: now, wordCount: countWords(preset.content) };
    const updated = [newNote, ...notes]; setNotes(updated); persistNotes(updated); setActiveNoteId(newNote.id); setActiveView('editor'); setMobileSidebarOpen(false); setCommandOpen(false); setTemplateOpen(false); toast.success(template === 'blank' ? 'New note created' : `${preset.label} created`);
  }, [notes, persistNotes]);
  const updateNote = useCallback((id: string, changes: Partial<Note>) => { setNotes(prev => { const updated = prev.map(n => n.id !== id ? n : { ...n, ...changes, updatedAt: new Date().toISOString(), wordCount: changes.content !== undefined ? countWords(changes.content) : n.wordCount }); if (saveTimeoutRef.current) clearTimeout(saveTimeoutRef.current); saveTimeoutRef.current = setTimeout(() => persistNotes(updated), 700); return updated; }); }, [persistNotes]);
  const deleteNote = useCallback((id: string) => { setNotes(prev => { const updated = prev.filter(n => n.id !== id); persistNotes(updated); return updated; }); if (activeNoteId === id) { setActiveNoteId(null); setActiveView('home'); } setDeleteTarget(null); toast.success('Note deleted'); }, [activeNoteId, persistNotes]);
  const duplicateNote = useCallback((id: string) => { const source = notes.find(n => n.id === id); if (!source) return; const now = new Date().toISOString(); const dup: Note = { ...source, id: `note-${Date.now()}`, title: `${source.title} (copy)`, createdAt: now, updatedAt: now }; const updated = [dup, ...notes]; setNotes(updated); persistNotes(updated); toast.success('Note duplicated'); }, [notes, persistNotes]);
  const togglePin = useCallback((id: string) => { const note = notes.find(n => n.id === id); updateNote(id, { isPinned: !note?.isPinned }); toast.success(note?.isPinned ? 'Note unpinned' : 'Note pinned'); }, [notes, updateNote]);
  const toggleFavorite = useCallback((id: string) => { const note = notes.find(n => n.id === id); updateNote(id, { isFavorite: !note?.isFavorite }); toast.success(note?.isFavorite ? 'Removed from favorites' : 'Added to favorites'); }, [notes, updateNote]);
  const createFolder = useCallback((name: string, color: string) => { const folder: Folder = { id: `folder-${Date.now()}`, name, color, createdAt: new Date().toISOString() }; const updated = [...folders, folder]; setFolders(updated); saveFolders(updated); toast.success(`Folder "${name}" created`); }, [folders]);
  const handleInsertIntoNote = useCallback((text: string) => { if (!activeNoteId) { toast.error('Open a note first to insert content.'); return; } setInsertContent(text); setActiveView('editor'); }, [activeNoteId]);
  const toggleTheme = () => { const next = !darkMode; setDarkMode(next); document.documentElement.classList.toggle('dark', next); localStorage.setItem('smartnotepad_theme', next ? 'dark' : 'light'); };

  useEffect(() => { const handler = (e: KeyboardEvent) => { const ctrl = e.ctrlKey || e.metaKey; if (ctrl && e.key.toLowerCase() === 'n') { e.preventDefault(); setTemplateOpen(true); } if (ctrl && e.key.toLowerCase() === 'k') { e.preventDefault(); setCommandOpen(v => !v); } if (ctrl && e.shiftKey && e.key.toLowerCase() === 'f') { e.preventDefault(); setSearchPanelOpen(true); } if (e.key === 'Escape') { setCommandOpen(false); setMobileSidebarOpen(false); setTemplateOpen(false); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);

  return <div className="flex h-screen bg-background overflow-hidden text-foreground">
    {mobileSidebarOpen && <div className="fixed inset-0 bg-slate-950/35 backdrop-blur-[2px] z-40 lg:hidden" onClick={() => setMobileSidebarOpen(false)} />}
    <div className={`fixed lg:relative inset-y-0 left-0 z-50 lg:z-auto transition-transform duration-300 ${mobileSidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'} ${sidebarOpen ? 'w-[272px]' : 'w-[68px]'}`}><NotesSidebar notes={notes} folders={folders} activeNoteId={activeNoteId} searchQuery={searchQuery} isCollapsed={!sidebarOpen} onSearchChange={setSearchQuery} onSelectNote={id => { setActiveNoteId(id); setActiveView('editor'); setMobileSidebarOpen(false); }} onCreateNote={() => setTemplateOpen(true)} onTogglePin={togglePin} onToggleFavorite={toggleFavorite} onDuplicate={duplicateNote} onDelete={id => setDeleteTarget(id)} onToggleCollapse={() => setSidebarOpen(v => !v)} onCreateFolder={() => setShowFolderModal(true)} onGoHome={() => { setActiveView('home'); setActiveNoteId(null); setMobileSidebarOpen(false); }} /></div>
    <div className="flex-1 min-w-0 flex flex-col overflow-hidden">
      <header className="hidden lg:flex h-[72px] shrink-0 items-center gap-5 border-b border-border bg-card/90 backdrop-blur-xl px-5 xl:px-7"><div className="flex items-center gap-3 min-w-[180px]"><AppLogo size={32}/><span className="font-bold tracking-tight">Smart<span className="text-primary">Notepad</span></span></div><button onClick={() => setCommandOpen(true)} className="app-control h-10 flex-1 max-w-[620px] mx-auto px-3.5 flex items-center gap-3 text-sm text-muted-foreground text-left"><Search size={16}/><span className="flex-1">Search notes, commands, and ideas…</span><kbd className="rounded-md border border-border bg-muted px-1.5 py-0.5 text-[10px]">Ctrl K</kbd></button><div className="flex items-center gap-1.5 min-w-[180px] justify-end"><button onClick={() => setSearchPanelOpen(v => !v)} className="toolbar-btn" title="Web search"><Sparkles size={18}/></button><button onClick={() => setTemplateOpen(true)} className="toolbar-btn" title="New note (Ctrl+N)"><Plus size={18}/></button><button onClick={toggleTheme} className="toolbar-btn" title="Toggle theme">{darkMode ? <Sun size={18}/> : <Moon size={18}/>}</button><button onClick={() => router.push('/settings')} className="toolbar-btn" title="Settings"><Settings size={18}/></button><div className="ml-2 grid h-9 w-9 place-items-center rounded-full bg-secondary text-primary text-sm font-bold">K</div></div></header>
      <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-card lg:hidden"><button onClick={() => setMobileSidebarOpen(true)} className="toolbar-btn"><Menu size={20}/></button><span className="text-sm font-semibold truncate max-w-[55%]">{activeView === 'editor' && activeNote ? activeNote.title : 'SmartNotepad'}</span><button onClick={() => setSearchPanelOpen(v => !v)} className="toolbar-btn"><PanelRight size={19}/></button></div>
      <div className="flex-1 flex overflow-hidden"><div className="flex-1 min-w-0 overflow-hidden">{activeView === 'home' ? <DashboardHome notes={notes} folders={folders} onCreateNote={() => setTemplateOpen(true)} onSelectNote={id => { setActiveNoteId(id); setActiveView('editor'); }} onOpenSearch={() => setSearchPanelOpen(true)} /> : activeNote ? <NoteEditor note={activeNote} folders={folders} onUpdate={updateNote} onTogglePin={() => togglePin(activeNote.id)} onToggleFavorite={() => toggleFavorite(activeNote.id)} onDelete={() => setDeleteTarget(activeNote.id)} onDuplicate={() => duplicateNote(activeNote.id)} onToggleSearch={() => setSearchPanelOpen(v => !v)} searchPanelOpen={searchPanelOpen} insertContent={insertContent} onInsertConsumed={() => setInsertContent(null)} /> : <div className="h-full grid place-items-center text-sm text-muted-foreground">Select a note or create a new one</div>}</div><div className={`fixed right-0 top-0 h-full lg:relative lg:top-auto lg:right-auto w-80 xl:w-96 bg-card border-l border-border transition-transform duration-300 z-30 overflow-hidden ${searchPanelOpen ? 'translate-x-0' : 'translate-x-full lg:translate-x-full lg:w-0 lg:border-0'}`}>{searchPanelOpen && <div className="h-full flex flex-col"><div className="h-[72px] flex items-center justify-between px-5 border-b border-border"><div><p className="text-sm font-semibold">Web search</p><p className="text-[11px] text-muted-foreground">Research without leaving your notes</p></div><button onClick={() => setSearchPanelOpen(false)} className="toolbar-btn"><X size={17}/></button></div><WebSearchPanel onInsertIntoNote={handleInsertIntoNote} hasActiveNote={!!activeNoteId}/></div>}</div></div>
    </div>

    {templateOpen && <div className="fixed inset-0 z-[90] bg-slate-950/30 backdrop-blur-sm p-4 grid place-items-center" onClick={() => setTemplateOpen(false)}><div className="w-full max-w-2xl rounded-2xl border border-border bg-card shadow-2xl p-5 sm:p-6" onClick={e => e.stopPropagation()}><div className="flex items-start justify-between mb-5"><div><p className="text-xs font-semibold text-primary">Create something useful</p><h2 className="text-xl font-bold tracking-tight mt-1">Choose a note template</h2><p className="text-sm text-muted-foreground mt-1">Start blank or jump straight into a structured workflow.</p></div><button onClick={() => setTemplateOpen(false)} className="toolbar-btn"><X size={17}/></button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{(Object.entries(TEMPLATES) as [NoteTemplate, typeof TEMPLATES[NoteTemplate]][]).map(([key,item]) => <button key={key} onClick={() => createNote(key)} className="group text-left rounded-xl border border-border p-4 hover:border-primary/40 hover:bg-secondary/50 transition-all"><span className="grid h-10 w-10 place-items-center rounded-xl bg-muted text-primary group-hover:bg-card"><item.icon size={18}/></span><p className="mt-3 text-sm font-semibold">{item.label}</p><p className="mt-1 text-xs text-muted-foreground">{key==='daily'?'Plan and reflect on your day.':key==='study'?'Capture concepts, questions, and summaries.':key==='meeting'?'Keep decisions and action items together.':key==='project'?'Turn an idea into a clear execution plan.':'A clean canvas for anything.'}</p></button>)}</div><div className="mt-5 pt-4 border-t border-border text-[10px] text-muted-foreground">Tip: Ctrl + N opens the template picker.</div></div></div>}
    {commandOpen && <div className="fixed inset-0 z-[80] bg-slate-950/30 backdrop-blur-sm p-4 sm:p-8" onClick={() => setCommandOpen(false)}><div className="mx-auto mt-[10vh] w-full max-w-xl overflow-hidden rounded-2xl border border-border bg-card shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-4 py-4"><Command size={18} className="text-primary"/><input autoFocus value={searchQuery} onChange={e => setSearchQuery(e.target.value)} placeholder="Search your notes or type a command…" className="flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"/><kbd className="text-[10px] text-muted-foreground">ESC</kbd></div><div className="p-2"><button onClick={() => {setCommandOpen(false);setTemplateOpen(true)}} className="w-full flex items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-muted"><span className="grid h-8 w-8 place-items-center rounded-lg bg-secondary text-primary"><Plus size={15}/></span><span className="text-sm font-medium">Create from template</span><span className="ml-auto text-muted-foreground">›</span></button><button onClick={() => {setActiveView('home');setCommandOpen(false)}} className="w-full flex items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-muted"><span className="grid h-8 w-8 place-items-center rounded-lg bg-secondary text-primary"><LayoutDashboard size={15}/></span><span className="text-sm font-medium">Open dashboard</span><span className="ml-auto text-muted-foreground">›</span></button><button onClick={() => {setSearchPanelOpen(true);setCommandOpen(false)}} className="w-full flex items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-muted"><span className="grid h-8 w-8 place-items-center rounded-lg bg-secondary text-primary"><Sparkles size={15}/></span><span className="text-sm font-medium">Open web research</span><span className="ml-auto text-muted-foreground">›</span></button><button onClick={() => router.push('/settings')} className="w-full flex items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-muted"><span className="grid h-8 w-8 place-items-center rounded-lg bg-secondary text-primary"><Settings size={15}/></span><span className="text-sm font-medium">Open settings</span><span className="ml-auto text-muted-foreground">›</span></button></div><div className="border-t border-border px-4 py-3 text-[10px] text-muted-foreground">Ctrl + N creates from a template · Ctrl + K opens commands · Ctrl + Shift + F opens web research</div></div></div>}
    {showFolderModal && <FolderModal onClose={() => setShowFolderModal(false)} onCreate={createFolder}/>} {deleteTarget && <DeleteModal noteTitle={notes.find(n => n.id === deleteTarget)?.title ?? 'this note'} onClose={() => setDeleteTarget(null)} onConfirm={() => deleteNote(deleteTarget)}/>} 
  </div>;
}
