'use client';

import React, { useMemo, useState } from 'react';
import { Plus, Search, Pin, Star, Folder, Home, ChevronLeft, ChevronRight, MoreHorizontal, Trash2, Copy, PinOff, StarOff, FolderPlus, FileText, Settings, SlidersHorizontal } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { type Note, type Folder as FolderType, formatRelativeTime } from '@/lib/notesStorage';
import AppLogo from '@/components/ui/AppLogo';

type SortMode = 'newest' | 'oldest' | 'title' | 'favorites';
type FilterMode = 'all' | 'pinned' | 'favorites' | string;
interface Props {
  notes: Note[]; folders: FolderType[]; activeNoteId: string | null; searchQuery: string; isCollapsed: boolean;
  onSearchChange: (q: string) => void; onSelectNote: (id: string) => void; onCreateNote: () => void;
  onTogglePin: (id: string) => void; onToggleFavorite: (id: string) => void; onDuplicate: (id: string) => void;
  onDelete: (id: string) => void; onToggleCollapse: () => void; onCreateFolder: () => void; onGoHome: () => void;
}

export default function NotesSidebar({ notes, folders, activeNoteId, searchQuery, isCollapsed, onSearchChange, onSelectNote, onCreateNote, onTogglePin, onToggleFavorite, onDuplicate, onDelete, onToggleCollapse, onCreateFolder, onGoHome }: Props) {
  const router = useRouter(); const [filter, setFilter] = useState<FilterMode>('all'); const [sort, setSort] = useState<SortMode>('newest'); const [openMenuId, setOpenMenuId] = useState<string | null>(null);
  const filteredNotes = useMemo(() => {
    let list = notes;
    const q = searchQuery.trim().toLowerCase();
    if (q) list = list.filter(n => n.title.toLowerCase().includes(q) || n.content.replace(/<[^>]*>/g, ' ').toLowerCase().includes(q));
    if (filter === 'pinned') list = list.filter(n => n.isPinned); else if (filter === 'favorites') list = list.filter(n => n.isFavorite); else if (filter !== 'all') list = list.filter(n => n.folderId === filter);
    return [...list].sort((a, b) => sort === 'oldest' ? new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime() : sort === 'title' ? a.title.localeCompare(b.title) : sort === 'favorites' ? Number(b.isFavorite) - Number(a.isFavorite) : new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
  }, [notes, searchQuery, filter, sort]);
  const pinnedCount = notes.filter(n => n.isPinned).length; const favCount = notes.filter(n => n.isFavorite).length;

  const iconButton = (active = false) => `grid h-9 w-9 place-items-center rounded-lg transition-colors ${active ? 'bg-secondary text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`;
  if (isCollapsed) return <div className="flex h-full w-[68px] flex-col items-center border-r border-border bg-card py-4 gap-2"><AppLogo size={34} className="mb-3"/><button onClick={onCreateNote} className="app-primary grid h-10 w-10 place-items-center" title="New note"><Plus size={19}/></button><button onClick={onGoHome} className={iconButton()} title="Home"><Home size={18}/></button><button onClick={() => setFilter('all')} className={iconButton(filter === 'all')} title="All notes"><FileText size={18}/></button><button onClick={() => setFilter('pinned')} className={iconButton(filter === 'pinned')} title="Pinned"><Pin size={18}/></button><button onClick={() => setFilter('favorites')} className={iconButton(filter === 'favorites')} title="Favorites"><Star size={18}/></button><div className="flex-1"/><button onClick={() => router.push('/settings')} className={iconButton()} title="Settings"><Settings size={18}/></button><button onClick={onToggleCollapse} className={iconButton()} title="Expand sidebar"><ChevronRight size={18}/></button></div>;

  return <aside className="flex h-full w-[272px] flex-col bg-card border-r border-border overflow-hidden">
    <div className="flex items-center justify-between px-4 py-4 border-b border-border shrink-0"><div className="flex items-center gap-2.5 min-w-0"><AppLogo size={34}/><div className="min-w-0"><p className="text-[15px] font-bold tracking-tight truncate">Smart<span className="text-primary">Notepad</span></p><p className="text-[10px] text-muted-foreground truncate">Write. Organize. Think better.</p></div></div><button onClick={onToggleCollapse} className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground hover:bg-muted hover:text-foreground" title="Collapse sidebar"><ChevronLeft size={16}/></button></div>
    <div className="px-3 pt-3 pb-2 shrink-0"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"/><input value={searchQuery} onChange={e => onSearchChange(e.target.value)} placeholder="Search notes…" className="app-control w-full h-10 pl-9 pr-12 text-xs bg-input focus:bg-card"/><kbd className="absolute right-2.5 top-1/2 -translate-y-1/2 rounded-md border border-border bg-card px-1.5 py-0.5 text-[9px] font-medium text-muted-foreground">⌘K</kbd></div></div>
    <div className="px-3 pb-3 shrink-0"><button onClick={onCreateNote} className="app-primary w-full h-10 flex items-center justify-center gap-2 text-sm font-semibold"><Plus size={16}/> New note <span className="ml-auto text-[10px] opacity-70">Ctrl N</span></button></div>
    <nav className="px-3 pb-3 space-y-1 shrink-0">
      <button onClick={onGoHome} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium ${filter === 'home' ? 'bg-secondary text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Home size={16}/> Home</button>
      {[{key:'all', icon:FileText, label:'All notes', count:notes.length},{key:'pinned',icon:Pin,label:'Pinned',count:pinnedCount},{key:'favorites',icon:Star,label:'Favorites',count:favCount}].map(item => <button key={item.key} onClick={() => setFilter(item.key as FilterMode)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium ${filter === item.key ? 'bg-secondary text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><item.icon size={16}/><span className="flex-1 text-left">{item.label}</span><span className="text-[10px] min-w-5 text-center rounded-full bg-muted px-1.5 py-0.5">{item.count}</span></button>)}
    </nav>
    <div className="px-3 pb-2 shrink-0"><div className="flex items-center px-3 mb-1"><span className="flex-1 text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">Folders</span><button onClick={onCreateFolder} className="grid h-7 w-7 place-items-center rounded-lg text-muted-foreground hover:bg-muted hover:text-foreground"><FolderPlus size={14}/></button></div>{folders.slice(0,5).map(folder => <button key={folder.id} onClick={() => setFilter(folder.id)} className={`w-full flex items-center gap-3 px-3 py-2 rounded-xl text-sm ${filter === folder.id ? 'bg-secondary text-primary font-medium' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Folder size={15} style={{color:folder.color}}/><span className="flex-1 text-left truncate">{folder.name}</span><span className="text-[10px]">{notes.filter(n => n.folderId === folder.id).length}</span></button>)}</div>
    <div className="flex items-center gap-2 px-4 pb-2 pt-1 shrink-0"><span className="text-[10px] font-semibold text-muted-foreground flex-1">{filteredNotes.length} notes</span><SlidersHorizontal size={12} className="text-muted-foreground"/><select value={sort} onChange={e => setSort(e.target.value as SortMode)} className="bg-transparent text-[10px] text-muted-foreground outline-none"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="title">Title</option><option value="favorites">Favorites</option></select></div>
    <div className="flex-1 overflow-y-auto scrollbar-thin px-2 pb-3">
      {filteredNotes.length === 0 ? <div className="py-12 px-5 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-secondary text-primary"><FileText size={19}/></div><p className="mt-3 text-sm font-semibold">Nothing here yet</p><p className="mt-1 text-xs text-muted-foreground">Create a note or change your filter.</p></div> : filteredNotes.map(note => { const folder = folders.find(f => f.id === note.folderId); const snippet = note.content.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim().slice(0,72); return <div key={note.id} onClick={() => onSelectNote(note.id)} className={`group relative cursor-pointer rounded-xl border px-3 py-3 mb-1.5 note-card-hover ${activeNoteId === note.id ? 'border-primary/25 bg-secondary/55 shadow-sm' : 'border-transparent hover:border-border hover:bg-muted/70'}`}>
        <div className="flex items-start gap-2"><div className={`mt-0.5 h-7 w-7 shrink-0 rounded-lg grid place-items-center ${activeNoteId === note.id ? 'bg-card text-primary' : 'bg-muted text-muted-foreground'}`}><FileText size={13}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-1"><p className="text-xs font-semibold truncate">{note.title}</p>{note.isPinned && <Pin size={10} className="text-primary shrink-0"/>}{note.isFavorite && <Star size={10} className="text-amber-500 fill-amber-500 shrink-0"/>}</div>{snippet && <p className="mt-1 text-[10px] leading-4 text-muted-foreground line-clamp-2">{snippet}</p>}<div className="mt-2 flex items-center gap-2 text-[9px] text-muted-foreground/75"><span>{formatRelativeTime(note.updatedAt)}</span>{folder && <span className="truncate" style={{color:folder.color}}>{folder.name}</span>}<span className="ml-auto">{note.wordCount}w</span></div></div><button onClick={e => { e.stopPropagation(); setOpenMenuId(openMenuId === note.id ? null : note.id); }} className="opacity-0 group-hover:opacity-100 grid h-7 w-7 place-items-center rounded-lg hover:bg-card text-muted-foreground"><MoreHorizontal size={14}/></button></div>
        {openMenuId === note.id && <div onClick={e => e.stopPropagation()} className="absolute right-2 top-10 z-40 w-40 rounded-xl border border-border bg-card shadow-xl p-1.5 fade-in">{[{icon:note.isPinned?PinOff:Pin,label:note.isPinned?'Unpin':'Pin',action:()=>onTogglePin(note.id)},{icon:note.isFavorite?StarOff:Star,label:note.isFavorite?'Unfavorite':'Favorite',action:()=>onToggleFavorite(note.id)},{icon:Copy,label:'Duplicate',action:()=>onDuplicate(note.id)},{icon:Trash2,label:'Delete',action:()=>onDelete(note.id)}].map(item => <button key={item.label} onClick={() => {item.action();setOpenMenuId(null)}} className="w-full flex items-center gap-2 px-2.5 py-2 rounded-lg text-xs text-muted-foreground hover:bg-muted hover:text-foreground"><item.icon size={13}/>{item.label}</button>)}</div>}
      </div> })}
    </div>
    <div className="border-t border-border px-3 py-3 shrink-0"><button onClick={() => router.push('/settings')} className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm text-muted-foreground hover:bg-muted hover:text-foreground"><Settings size={16}/><span>Settings</span><ChevronRight size={14} className="ml-auto"/></button></div>
  </aside>;
}
